<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="SQLLOG" Id="{036539be-4e58-4914-8edb-b580a4f22671}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM SQLLOG

VAR
	

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="SQLLOG">
      <LineId Id="11" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>